# These are supported funding model platforms

##  Support via UPI (for Indian users)

You can support me directly using any UPI app (Google Pay, PhonePe, Paytm, BHIM, etc.):

**UPI ID:** `jazzboss@upi`  
Scan the QR code below to pay:

![UPI QR](link-to-your-qr-code-image)


